Implemented: Gitbook lens search feature
hotwax/company pull request #24
Opened 2024-06-07 14:22 UTC by amansinghbais

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/company#contribution-guideline)

2024-06-14 10:24 UTC, ymaheshwari1 requested changes

2024-06-14 10:24 UTC, ymaheshwari1 commented on src/services/UtilService.ts
> +import { hasError } from "@/utils";
Remove unused imports.

2024-06-14 10:24 UTC, ymaheshwari1 commented on src/services/UtilService.ts
> +    url: `ask`,
```suggestion
    url: "ask" 
```

2024-06-14 10:24 UTC, ymaheshwari1 commented on src/services/UtilService.ts
> +      "Access-Control-Allow-Origin":   "*"
I think this is not required.

2024-06-14 10:24 UTC, ymaheshwari1 commented on src/services/UtilService.ts
> +const getGitboookPage = async (pageId: any): Promise <any> => {
```suggestion
const getGitBookPage = async (pageId: any): Promise <any> => {
```

2024-06-14 10:24 UTC, ymaheshwari1 commented on src/services/UtilService.ts
> +  const baseURL = `https://api.gitbook.com/v1/spaces/${process.env.VUE_APP_SPACE_ID}/`
We can keep the gitbook api endpoint in the env `https://api.gitbook.com/v1/spaces/`

```suggestion
  const baseURL = `https://api.gitbook.com/v1/spaces/${process.env.VUE_APP_SPACE_ID}/`
```

2024-06-14 11:08 UTC, ymaheshwari1 requested changes

2024-06-14 11:08 UTC, ymaheshwari1 commented on src/components/GitBookSearch.vue
> +  isQueryFetching.value = true;
```suggestion
  isLoading.value = true;
```

2024-06-14 13:33 UTC, ymaheshwari1 approved these changes

2024-06-17 13:53 UTC, ymaheshwari1 requested changes

2024-07-10 06:04 UTC, amansinghbais commented
Has implemented this with different approach in following PR : https://github.com/hotwax/company/pull/26

2024-07-10 06:04 UTC, closed without merging