Implemented: NetSuite Integration Management UI(#37)
hotwax/company pull request #38
Opened 2024-09-28 13:22 UTC by R-Sourabh

### Related Issues

#37 

### Short Description and Why It's Useful

- Implemented the UI for the NetSuite Integration Management.

### Screenshots of Visual Changes before/after (If There Are Any)

### Contribution and Currently Important Rules Acceptance

- [X] I read and followed [contribution rules](https://github.com/hotwax/company#contribution-guideline)

2024-10-05 01:16 UTC, dt2patel requested changes
See comments

2024-10-05 01:16 UTC, dt2patel commented on src/views/NetSuite.vue
> +main {
why use main element here? we can simply just add ion padding to ion content right? @R-Sourabh

2024-10-05 01:16 UTC, dt2patel commented on src/views/NetSuite.vue
> +            <ion-card>
we shouldn't use ion-card here. Like in Figma, directly use ion item with outline and border radius. We should make this a global style in our app themes. We use this item pattern in the fulfillment app and I expect to use it again. @R-Sourabh

2024-10-05 01:16 UTC, dt2patel commented on src/views/NetSuite.vue
> +          <section>
I think this UI patter in itself will be, or has been frequently reused. Lets make a DXP component where you can pass in:

list of item labels and p tags in labels. You can also pass in the action icon that will be displayed on each of the items' end slots.

something like:

title: section-name
itemEndIcon: icon-name
items: [{primary label, secondary label}]

2024-10-05 07:42 UTC, R-Sourabh commented on src/views/NetSuite.vue
> +main {
Yeah, sure sir.

2024-10-05 07:52 UTC, R-Sourabh commented on src/views/NetSuite.vue
> +            <ion-card>
I misunderstood that sir, I'll change it.

2024-10-05 10:37 UTC, R-Sourabh commented on src/views/NetSuite.vue
> +          <section>
Sure, I'll look into this.

2024-10-12 03:38 UTC, dt2patel requested changes
Some more feedback

2024-10-12 03:38 UTC, dt2patel commented on src/views/NetSuite.vue
> +  border-radius: 8px;
why not just use the ion item custom property for border radius? 
https://ionicframework.com/docs/api/item#css-custom-properties-1

--border-radius

2024-10-12 03:38 UTC, dt2patel commented on src/views/NetSuite.vue
> +  gap: 10px;
use spacer variables here instead of hard coded value. I know you are recreating the default margin of ion card, but if you're replacing, it is recommended to use premade spacer.

2025-02-13 11:19 UTC, ymaheshwari1 requested changes

2025-02-13 11:19 UTC, ymaheshwari1 commented on src/views/PaymentMethods.vue
> +          <p>orders</p>
Add internationalization

2025-02-13 11:19 UTC, ymaheshwari1 commented on src/views/PaymentMethods.vue
> +import { IonButton, IonChip, IonContent, IonHeader, IonIcon, IonItem, IonLabel, IonPage, IonMenuButton, IonTitle, IonToolbar, onIonViewWillEnter, alertController } from "@ionic/vue";
Use same import

2025-02-27 12:33 UTC, ymaheshwari1 requested changes

2025-03-05 13:23 UTC, merged